apiVersion: apps/v1
kind: Deployment
metadata:
  name: callView
  labels:
    app: callView
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callView
  template:
    metadata:
      labels:
        app: callView
    spec:
      containers:
        - name: callView
          image: username/callView:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5